issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - errcheck
    - linters:
        - errcheck
      # allow defer statements without error checks
      source: "^\\s*defer\\s+"
