---
- name: Start VMs
  hosts: localhost
  become: false
  roles:
    - role: start_vms

- name: Install prerequisites
  hosts: all
  become: true
  roles:
    - role: rhel_prerequisites
      when: ansible_facts['os_family'] == "RedHat"
    - role: deb_prerequisites
      when: ansible_facts['os_family'] == "Debian"

- name: Write test configs
  hosts: localhost
  gather_facts: false
  roles:
    - role: generate_test_config
