---
- name: Start VMs
  hosts: localhost
  become: false
  roles:
    - role: start_vms

- name: Install prerequisites
  hosts: all
  become: true
  roles:
    - role: install_prerequisites

- name: Write test configs
  hosts: localhost
  gather_facts: false
  roles:
    - role: generate_test_config
